---

- name: Configure L3 interfaces on PODX_SPINE21
  connection: local
  gather_facts: no
  hosts: PODX_SPINE21

  tasks:
    - name: configure PODX_SPINE21 loopbacks
      cisco.nxos.nxos_l3_interfaces:
        config:
         - name: Loopback0
           ipv4:
           - address: 10.1X.126.1/32
           ipv6:
           - address: 2001:db8:10:1X::126:1/128
         - name: Loopback100
           ipv4:
           - address: 10.1X.192.1/32
           ipv6:
           - address: 2001:db8:10:1X::192:1/128

    - name: PODX_SPINE21 Ethernet1/1 and Ethernet1/2 to routed iface
      cisco.nxos.nxos_interfaces:
         config:
          - name: Ethernet1/1
            description: To LEAF switches
            enabled: true
            mode: layer3
          - name: Ethernet1/2
            description: To LEAF switches
            enabled: true
            mode: layer3

    - name: PODX_SPINE21 Ethernet1/1 and 1/2 layer 3 information
      cisco.nxos.nxos_l3_interfaces:
        config:
         - name: Ethernet1/1
           ipv4:
           - address: 10.1X.126.129/30
         - name: Ethernet1/2
           ipv4:
           - address: 10.1X.126.138/30

- name: Configure L3 interfaces on PODX_SPINE22
  connection: local
  gather_facts: no
  hosts: PODX_SPINE22

  tasks:
    - name: configure PODX_SPINE21 loopbacks
      cisco.nxos.nxos_l3_interfaces:
        config:
         - name: Loopback0
           ipv4:
           - address: 10.1X.126.2/32
           ipv6:
           - address: 2001:db8:10:1X::126:2/128
         - name: Loopback100
           ipv4:
           - address: 10.1X.192.2/32
           ipv6:
           - address: 2001:db8:10:1X::192:2/128

    - name: PODX_SPINE22 Ethernet1/1 and Ethernet1/2 to routed iface
      cisco.nxos.nxos_interfaces:
         config:
          - name: Ethernet1/1
            description: To LEAF switches
            enabled: true
            mode: layer3
          - name: Ethernet1/2
            description: To LEAF switches
            enabled: true
            mode: layer3

    - name: PODX_SPINE22 Ethernet1/1 and 1/2 layer 3 information
      cisco.nxos.nxos_l3_interfaces:
        config:
         - name: Ethernet1/1
           ipv4:
           - address: 10.1X.126.133/30
         - name: Ethernet1/2
           ipv4:
           - address: 10.1X.126.141/30

- name: Configure L3 interfaces on PODX_LEAF11
  connection: local
  gather_facts: no
  hosts: PODX_LEAF11

  tasks:
    - name: configure PODX_LEAF11 loopbacks
      cisco.nxos.nxos_l3_interfaces:
        config:
          - name: Loopback0
            ipv4:
            - address: 10.1X.126.3/32
            ipv6:
            - address: 2001:db8:10:1X::126:3/128
          - name: Loopback100
            ipv4:
            - address: 10.1X.192.3/32
            ipv6:
            - address: 2001:db8:10:1X::192:3/128
    - name: PODX_LEAF11 Ethernet1/1 and Ethernet1/2 to routed iface
      cisco.nxos.nxos_interfaces:
         config:
          - name: Ethernet1/1
            description: To SPINE switches
            enabled: true
            mode: layer3
          - name: Ethernet1/2
            description: To SPINE switches
            enabled: true
            mode: layer3
    - name: PODX_SPINE22 Ethernet1/1 and 1/2 layer 3 information
      cisco.nxos.nxos_l3_interfaces:
        config:
         - name: Ethernet1/1
           ipv4:
           - address: 10.1X.126.130/30
         - name: Ethernet1/2
           ipv4:
           - address: 10.1X.126.134/30

- name: Configure L3 interfaces on PODX_LEAF12
  connection: local
  gather_facts: no
  hosts: PODX_LEAF12

  tasks:
    - name: configure PODX_LEAF12 loopbacks
      cisco.nxos.nxos_l3_interfaces:
        config:
          - name: Loopback0
            ipv4:
            - address: 10.1X.126.4/32
            ipv6:
            - address: 2001:db8:10:1X::126:4/128
          - name: Loopback100
            ipv4:
            - address: 10.1X.192.4/32
            ipv6:
            - address: 2001:db8:10:1X::192:4/128
    - name: PODX_LEAF12 Ethernet1/1 and Ethernet1/2 to routed iface
      cisco.nxos.nxos_interfaces:
         config:
          - name: Ethernet1/1
            description: To SPINE switches
            enabled: true
            mode: layer3
          - name: Ethernet1/2
            description: To SPINE switches
            enabled: true
            mode: layer3
    - name: PODX_LEAF12 Ethernet1/1 and 1/2 layer 3 information
      cisco.nxos.nxos_l3_interfaces:
        config:
         - name: Ethernet1/1
           ipv4:
           - address: 10.1X.126.137/30
         - name: Ethernet1/2
           ipv4:
           - address: 10.1X.126.142/30
