---

- name: "Nexus MP-BGP EVPN enablement"
  gather_facts: no
  hosts: PODX_SPINE21 PODX_SPINE22 PODX_LEAF11 PODX_LEAF12

  tasks:
    - name: Enable EVPN overlay feature
      nxos_evpn_global:
       nv_overlay_evpn: true

    - name: Configure L2EVPN RT in template peers
      nxos_config:
       lines:
        - address-family l2vpn evpn
        - retain route-target all
       parents: router bgp 6500X
       match: exact

    - name: Configure L2EVPN template for SPINEs
      when: inventory_hostname in ( 'PODX_SPINE21', 'PODX_SPINE22' )
      nxos_config:
       lines:
        - neighbor 10.1X.192.3
        - address-family l2vpn evpn
        - send-community
        - send-community extended
        - route-reflector-client
       parents: router bgp 6500X
       match: exact

    - name: Configure L2EVPN template for SPINEs
      when: inventory_hostname in ( 'PODX_SPINE21', 'PODX_SPINE22' )
      nxos_config:
       lines:
        - neighbor 10.1X.192.4
        - address-family l2vpn evpn
        - send-community
        - send-community extended
        - route-reflector-client
       parents: router bgp 6500X
       match: exact

    - name: Configure L2EVPN template for LEAFs
      when: inventory_hostname in ( 'PODX_LEAF11', 'PODX_LEAF12' )
      nxos_config:
       lines:
        - neighbor 10.1X.192.1
        - address-family l2vpn evpn
        - send-community
        - send-community extended
       parents: router bgp 6500X
       match: exact

    - name: Configure L2EVPN template for LEAFs
      when: inventory_hostname in ( 'PODX_LEAF11', 'PODX_LEAF12' )
      nxos_config:
       lines:
        - neighbor 10.1X.192.2
        - address-family l2vpn evpn
        - send-community
        - send-community extended
       parents: router bgp 6500X
       match: exact